In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('diabetes.csv')

In [3]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [5]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [6]:
X = df.drop(columns=['Outcome'])

In [7]:
y = df['Outcome']

In [8]:
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [9]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,
                                                test_size=0.2)

In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import VotingClassifier
import xgboost as xg
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import SVC

In [22]:
lr = LogisticRegression()

dt = DecisionTreeClassifier()

rf = RandomForestClassifier()

adr = AdaBoostClassifier()

br = BaggingClassifier(base_estimator=SVC(),n_estimators=10)

knr = KNeighborsClassifier()

vr = VotingClassifier([('lr', lr), ('rf', rf), ('knr', knr)])

gbr = GradientBoostingClassifier()

svr = SVC()

In [23]:
lr.fit(X_train,y_train)
dt.fit(X_train,y_train)
rf.fit(X_train,y_train)
adr.fit(X_train,y_train)
br.fit(X_train,y_train)
knr.fit(X_train,y_train)
vr.fit(X_train,y_train)
gbr.fit(X_train,y_train)
svr.fit(X_train,y_train)

c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
c:\users\hp\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

SVC()

In [24]:
y_pred1= lr.predict(X_test)
y_pred2= dt.predict(X_test)
y_pred3= rf.predict(X_test)
y_pred4= adr.predict(X_test)
y_pred5= br.predict(X_test)
y_pred6= knr.predict(X_test)
y_pred7= vr.predict(X_test)
y_pred8= gbr.predict(X_test)
y_pred8= svr.predict(X_test)

In [28]:
from sklearn.metrics import accuracy_score

In [29]:
r1=accuracy_score(y_test,y_pred1)
r2=accuracy_score(y_test,y_pred2)
r3=accuracy_score(y_test,y_pred3)
r4=accuracy_score(y_test,y_pred4)
r5=accuracy_score(y_test,y_pred5)
r6=accuracy_score(y_test,y_pred6)
r7=accuracy_score(y_test,y_pred7)
r8=accuracy_score(y_test,y_pred8)

In [30]:
print(r1 ,'\n',r2,'\n',r3,'\n',r4,'\n',r5,'\n',r6,'\n',r7,'\n',r8)

0.7272727272727273
 0.7077922077922078
 0.7337662337662337
 0.7207792207792207
 0.7142857142857143
 0.6428571428571429
 0.6948051948051948
 0.7142857142857143

In [31]:
import pickle
pickle.dump(lr,open('LRModel.pkl','wb'))
pickle.dump(dt,open('DTModel2.pkl','wb'))
pickle.dump(rf,open('RFModel.pkl','wb'))
pickle.dump(adr,open('ADRModel.pkl','wb'))
pickle.dump(br,open('BRModel.pkl','wb'))
pickle.dump(knr,open('KNRModel.pkl','wb'))
pickle.dump(vr,open('VRModel.pkl','wb'))
pickle.dump(gbr,open('GBRModel.pkl','wb'))
pickle.dump(svr,open('SVRModel.pkl','wb'))